# Generated by Django 2.2.24 on 2021-10-01 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicion',
            old_name='created_date',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='author',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='text',
        ),
        migrations.RemoveField(
            model_name='medicion',
            name='title',
        ),
        migrations.AddField(
            model_name='medicion',
            name='medicion',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='x',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='medicion',
            name='y',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='medicion',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
