# Generated by Django 2.2.24 on 2021-10-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211001_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicion',
            name='id_sensor',
            field=models.TextField(default='-sensor CO2'),
        ),
    ]
